<?php

namespace App\Tests\Service;
use App\Service\HomeService;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Contracts\HttpClient\HttpClientInterface;
use Psr\Log\LoggerInterface;
class HomeServiceTest extends WebTestCase
{
    protected $client;
    protected HomeService $service;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $urlFlux = 'http://www.commitstrip.com/en/feed/';
        $urlApi = 'https://newsapi.org/v2/top-headlines?country=us&apiKey=c782db1cd730403f88a544b75dc2d7a0';
        $httpClient = $this->getMockBuilder(HttpClientInterface::class)->getMock();
        $logger = $this->getMockBuilder(LoggerInterface::class)->getMock();
        $this->service = new HomeService($logger ,$httpClient,$urlFlux,$urlApi);
    }



    public function testGetImageFlux()
    {
        $imagesUrl = $this->service->getImageFlux();
        $this->assertIsArray($imagesUrl);

    }

    public function testGetImagesApi()
    {
        $imagesUrl = $this->service->getImagesApi();
        $this->assertIsArray($imagesUrl);
    }


}