<?php

namespace App\Tests\Controller;
use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
class HomeControllerTest extends WebTestCase
{ protected $client;
   public function setUp()
{
    parent::setUp(); // TODO: Change the autogenerated stub
    $this->client = static::createClient();
}

    public function testHomePage(){


     $this->client->request('GET', '/');

     $response = $this->client->getResponse();

     // On s'assure qu'il y a bien une page d'accueil
     $this->assertEquals(200, $response->getStatusCode());
 }
}